# Generated by Django 4.1.2 on 2022-10-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsq', '0003_rename_text_faq_answer_faq_question_delete_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(db_index=True)),
                ('answer', models.TextField(db_index=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'COVID'), (1, 'ACTIVIYIES'), (2, 'DCT'), (3, 'DESERT CAMPS'), (4, 'DUBAI ASSURED'), (5, 'DUBAI CALENDAR'), (6, 'DUBAI EXPERT'), (7, 'DUBAI WAY'), (8, 'EVENT PERMITS'), (9, 'EVENT SPONSORSHIP'), (10, 'EVENT TICKETING'), (11, 'HOLIDAY HOMES'), (12, 'HOTEL CLASSIFICATION'), (13, 'HOTEL MANAGEMENT'), (14, 'MEDYAF'), (15, 'EVENTS DET'), (16, 'SAFARI DRIVERS'), (17, 'SAFARIVEHICLES'), (18, 'SUPPLIERS'), (19, 'TOUR GUIDES'), (20, 'TRADE EVENTS')], db_index=True, default=0, verbose_name='type')),
            ],
        ),
    ]
