# Generated by Django 4.1.2 on 2022-10-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsq', '0004_faqar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'BOOLEAN MODEL'), (1, 'EXTENDED BOOLEAN MODEL'), (2, 'VECTOR MODEL')], default=0, verbose_name='Algorithm Type')),
            ],
        ),
    ]
